name: leak-check
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches: [main]
jobs:
  leak-check:
    uses: Matronhq/.github/.github/workflows/leak-check.yml@main
    secrets: inherit
